task 2
fs-anvr/medical_service pull request #2
Opened 2022-10-05 13:13 UTC by fs-anvr

added use case, test project and unit tests

2022-10-05 21:08 UTC, Vixorem requested changes

2022-10-05 21:08 UTC, Vixorem commented on domain/UserService.cs
> +    public Result CreateUser(string login, string password)
Давайте чтоб этот метод возвращал готового юзера если все норм

2022-10-05 21:08 UTC, Vixorem commented on unit-tests/UnitTest1.cs
> +    {
А как насчет кейса когда все ок?)

2022-10-05 21:08 UTC, Vixorem commented on unit-tests/UnitTest1.cs
> +public class UserServiceTests
Не хватает кейсов на userexists

2022-10-05 23:12 UTC, Vixorem requested changes
Так же хорошо если твой товарищ тебя поревьювит тоже

2022-10-05 23:12 UTC, Vixorem commented on unit-tests/UnitTests.cs
> +    public void CreateUserWhenRepositoryWork_ShouldOk()
В названии лучше более высокоуровнево объяснить, что юзер не найден или найден

2022-10-06 00:19 UTC, acceptTheVoid requested changes
Хорошо, мощно. Не считая прикола с паролем (в фефоруме мы трогали пароль напрямую только в функциях регистрации и логина) и Resultа-а (я не имею ни достаточно знаний этого богом забытого языка, ни достаточно желания, чтобы делать его более растоподобным) все очень даже хорошо.
В идеале еще хэшироаание паролей добавить, но это уже мелочи.

2022-10-06 00:19 UTC, acceptTheVoid commented on domain/IUserRepository.cs
> +    bool UserExists(string login, string password);
Я не думаю, что стоит запрашивать пароль, чтобы узнать существует ли пользователь с таким логином. В принципе пароль пользователя стоит хэшировать и больше не трогать, но это уже мелочи.

2022-10-06 00:19 UTC, acceptTheVoid commented on domain/UserService.cs
> +    }
Претензия про пароль все еще сохранена. Я не думаю что у метода такого высокого уровня должна быть потребность в пароле пользователя.

2022-10-06 00:24 UTC, Vixorem commented on domain/UserService.cs
> +    }
По хорошему, в таком методе должна происходить конвертация пароля в хэш, и потом должен сравниваться хэш пароля. Но это уже я оставил на потом

2022-10-06 00:29 UTC, Vixorem commented
Не знаю, как связан резалт и растоподобность, и не понимаю, к чему эти поверхностные суждения про забытый язык

2022-10-06 00:34 UTC, Vixorem requested changes

2022-10-06 00:34 UTC, Vixorem commented on domain/UserService.cs
> +            name: string.Empty,
Мы в этом методе создаем юзера. Юзер состоит не только из логина. Эти поля тоже должны быть заполнены

2022-10-06 00:53 UTC, fs-anvr commented on domain/UserService.cs
> +    }
Хэши будем потом делать, если я правильно понял?

При создании пользователя нужно передать в метод форму пользователя (и написать эту форму соот-но)?

2022-10-06 00:58 UTC, Vixorem commented on domain/UserService.cs
> +    }
Да, передавать параметры
По поводу хэша да. Я как то изначально не заложил это в ТЗ, возможно, стоило бы, но с другой стороны я ТЗ готовил так, чтобы показать, как можно подходить к разработке в похожих случаях. Но конечно если принимать во внимание безопасность, то эти пароли, приходящие на вход, мы должны конвертить в хэш и уже работать и сравнивать хэши. Но это, наверное, я постараюсь позже запросить, если будет случай

2022-10-07 03:08 UTC, Vixorem approved these changes
Кстати, необязательно запрашивать ревью у тех, кто уже

2022-10-07 03:14 UTC, acceptTheVoid approved these changes
Гигачад с большой челюстью

2022-10-07 03:15 UTC, merged