Task 3
fs-anvr/medical_service pull request #3
Opened 2022-10-18 06:08 UTC by fs-anvr

2022-10-18 06:37 UTC, DeadDogDance commented on domain/Forms/AppointmentForm.cs
> +
Думаю, вам следует добавить поля начала и конца приема.

2022-10-18 08:45 UTC, DeadDogDance approved these changes

2022-10-22 05:32 UTC, Vixorem requested changes

2022-10-22 05:32 UTC, Vixorem commented on domain/Entities/Appointment.cs
> +    {
Непонятно, зачем признак free

2022-10-22 05:32 UTC, Vixorem commented on domain/IAppointmentRepository.cs
> +    List<Appointment>? GetFreeDates(string specialization);
Appointment это по сути уже существующий прием. А своьодные даты это по сути несуществующие приемы. Тогда что ты будешь возвращать тут? Объекты с пустыми врачами и клиентами? Лучше возвращать даты

2022-10-22 05:32 UTC, Vixorem commented on domain/UseCases/AppointmentService.cs
> +    public Result<Appointment> CreateAppointment(AppointmentForm form)
А если на эту дату врач уже занят

2022-10-22 07:06 UTC, fs-anvr commented on domain/Entities/Appointment.cs
> +    {
предполагалось, что это признак того, взяла это запись кем-то или нет

2022-10-22 07:06 UTC, fs-anvr commented on domain/IAppointmentRepository.cs
> +    List<Appointment>? GetFreeDates(string specialization);
тогда не совсем понятно откуда брать несуществующие даты (для тестов например).

2022-10-22 07:07 UTC, Vixorem commented on domain/Entities/Appointment.cs
> +    {
Думаю лучше исходить из логики, что, если эта запись у нас существует, то она взята. А то иначе в ней смысла нет

2022-10-22 13:17 UTC, Vixorem commented on domain/IAppointmentRepository.cs
> +    List<Appointment>? GetFreeDates(string specialization);
Ну, тут да, тестировать как то не сильно много смысла имеет. Мокать данные, которые тупо возратить, как то смысла нет

2022-10-24 10:36 UTC, Vixorem requested changes

2022-10-24 10:36 UTC, Vixorem commented on domain/UseCases/AppointmentService.cs
> +    {
А если на эту дату уже доктор занят

2022-10-26 11:34 UTC, Vixorem approved these changes

2022-10-26 14:12 UTC, merged