Task 6 7
fs-anvr/medical_service pull request #6
Opened 2023-01-17 18:00 UTC by fs-anvr

2023-01-18 11:16 UTC, Vixorem requested changes

2023-01-18 11:16 UTC, Vixorem commented on domain/UseCases/AppointmentService.cs
> +            await appointmentSemaphore.WaitAsync();
Вот какой нюанс. Допустим, у нас 10 одновременных запросов, и все они касаются РАЗНЫХ врачей. А мы будем эти запросы блокировать и заставлять ждать. Надо что то придумать)

2023-01-18 11:16 UTC, Vixorem commented on repository/RepositoryImpl/DoctorRepositoryImpl.cs
> +        var doctor = _context.Doctors.FirstOrDefault(doctor => doctor.ID == id);
Кстати, есть асинхронная версия метода

2023-01-18 11:16 UTC, Vixorem commented on repository/RepositoryImpl/DoctorRepositoryImpl.cs
> +        await Task.Delay(0);
А это еще шо за делэй?

2023-01-18 11:16 UTC, Vixorem commented on repository/RepositoryImpl/DoctorRepositoryImpl.cs
> +        await Task.Delay(0);
У вас что ли не компилится без await, если метод асинхронный?)) ну, в вашем случае есть асинхронный FistOrDefaultAsync, но вообще по другому можно: убрать слово async, оставить Task, и при return обворачивать возвращаемое значение в Task.FromResult()

2023-01-18 15:31 UTC, fs-anvr commented on repository/RepositoryImpl/DoctorRepositoryImpl.cs
> +        var doctor = _context.Doctors.FirstOrDefault(doctor => doctor.ID == id);
найдём, улучшим)

2023-01-18 15:32 UTC, fs-anvr commented on repository/RepositoryImpl/DoctorRepositoryImpl.cs
> +        await Task.Delay(0);
это бесполезный delay, без него компилится, просто warning вылезает "async метод без await внутри". думаю это warning уйдёт при асинхронных запросах в бд

2023-01-18 16:39 UTC, fs-anvr commented
Переписал запросы на уровне бд на асинхронные аналоги (хотя в данном контексте это не даст выигрыша), также исправил семафоры. Теперь блокировка действительно происходит)

2023-01-19 04:26 UTC, fs-anvr commented
Убраны блокировки во всех сервисах, кроме Appointment. В Appointment блокирую при создании записи по DoctorID

2023-01-20 09:58 UTC, Vixorem approved these changes

2023-01-20 10:01 UTC, merged